
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // CLI (migrations) must use Neon's direct connection; the pooled one can time out on migration locks.
  datasource: {
    url: env("DATABASE_URL_UNPOOLED"),
  },
});
